linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - depguard
    - dogsled
    - errcheck
    - errchkjson
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - ineffassign
    - ireturn
    - maintidx
    - misspell
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - typecheck
    - unused
    - varcheck
